In [5]:
import pandas as pd 
import matplotlib.pyplot as plt 
import os

i_cloud_raw_data_path = "/Users/ottohartel/Library/Mobile Documents/com~apple~CloudDocs/Workout/raw_data"
i_cloud_parent = os.path.dirname(i_cloud_raw_data_path)
_all_runs = os.path.join(i_cloud_parent, "allRuns.csv")

In [7]:
data = pd.read_csv(_all_runs, sep = ";")
data.tail()

,start_time,end_time,duration_sec,distance_km,avg_hf,max_hf,avg_pace_sec,avg_speed_kmh,avg_cadence,total_energy_kcal,elev_gain_m,elev_loss_m,temp_c,notes
542,2025-12-28T16:12,2025-12-28T17:04,3146,7.04362,155.000000,168.0,446,8.058480652335431,128.924665,109.805,43.0,29.0,NaN,NaN
543,2026-01-03T14:09,2026-01-03T14:57,2883,6.55723,151.458333,164.0,439,8.186494923228452,135.821692,93.293,22.0,10.0,NaN,NaN
544,2026-01-07T17:04,2026-01-07T17:36,1903,4.13097,146.125000,158.0,460,7.813965896273899,131.807597,67.608,9.0,1.0,NaN,NaN
545,2026-01-10T15:26,2026-01-10T16:12,2783,6.03953,151.913043,161.0,460,7.81114787525949,129.347501,97.773,17.0,18.0,NaN,NaN
546,2026-01-17T20:47,2026-01-17T21:42,3319,7.51015,141.178571,158.0,441,8.145181999492202,134.150333,110.459,19.0,20.0,NaN,NaN

In [9]:
data = pd.read_csv(os.path.join(i_cloud_raw_data_path, "allWorkouts.csv"))
data.head()

,Type,Start,End,Duration,Distance,Average Heart Rate,Max Heart Rate,Average Pace,Average Speed,Average Cadence,Active Energy,Total Energy,Elevation Ascended,Elevation Descended,Weather Temperature,Weather Humidity
0,Outdoor Running,2026-02-19 17:09,2026-02-19 17:50,0:41:14,"5,5185","139,61904761904762",161,0:07:28,"8,027133175375694","128,22007282672786",NaN,"83,97999999999999",5,9.0,NaN,NaN
1,Outdoor Running,2026-02-12 17:36,2026-02-12 18:10,0:34:51,"4,68410009765625","148,1764705882353",159,0:07:26,"8,064274552476846","136,2847658643373",NaN,"90,62499999999999",27,16.0,NaN,NaN
2,Outdoor Running,2026-02-08 18:54,2026-02-08 19:24,0:30:09,"4,04027001953125","144,86666666666667",156,0:07:27,"8,03795234491299","133,0214061580971",NaN,"68,02799999999996",4,4.0,NaN,NaN
3,Outdoor Running,2026-02-03 18:42,2026-02-03 19:13,0:31:01,"4,1970498046875","137,46666666666667",154,0:07:23,"8,117556795533456","139,06823880267868",NaN,"78,04999999999998",5,8.0,NaN,NaN
4,Outdoor Running,2026-01-26 19:15,2026-01-26 19:48,0:33:16,"4,0563701171875","148,11764705882354",164,0:08:12,"7,315523052780005","129,24718707601426",NaN,"66,87200000000001",61,80.0,NaN,NaN

In [14]:
import datetime as dt

In [32]:
not_float_columns = ["Type", "Start", "End"] # "Duration"]
time_columns = ["Average Pace", "Duration"]
duration = "0:41:14"
time_format = "%H:%M:%S"
dur_dt = dt.datetime.strptime(duration, time_format)
hour , minute , second = dur_dt.hour, dur_dt.minute, dur_dt.second

In [33]:
hour

0

In [34]:
60*60*hour+60*minute+second

2474

In [26]:
for column in data.columns:
    if column in not_float_columns or data.dtypes[column] != "str":
        continue
    elif column in time_columns:
        data[column] = data[column].apply(lambda x: dt.datetime.strptime(x, time_format))
        continue
    print(column)
    data[column] = data[column].str.replace(",", ".")
    data[column] = data[column].astype(float)

Average Speed
Average Cadence
Total Energy
Elevation Ascended

In [28]:
data.head()

,Type,Start,End,Duration,Distance,Average Heart Rate,Max Heart Rate,Average Pace,Average Speed,Average Cadence,Active Energy,Total Energy,Elevation Ascended,Elevation Descended,Weather Temperature,Weather Humidity
0,Outdoor Running,2026-02-19 17:09,2026-02-19 17:50,1900-01-01 00:41:14,5.51850,139.619048,161,1900-01-01 00:07:28,8.027133,128.220073,NaN,83.980,5.0,9.0,NaN,NaN
1,Outdoor Running,2026-02-12 17:36,2026-02-12 18:10,1900-01-01 00:34:51,4.68410,148.176471,159,1900-01-01 00:07:26,8.064275,136.284766,NaN,90.625,27.0,16.0,NaN,NaN
2,Outdoor Running,2026-02-08 18:54,2026-02-08 19:24,1900-01-01 00:30:09,4.04027,144.866667,156,1900-01-01 00:07:27,8.037952,133.021406,NaN,68.028,4.0,4.0,NaN,NaN
3,Outdoor Running,2026-02-03 18:42,2026-02-03 19:13,1900-01-01 00:31:01,4.19705,137.466667,154,1900-01-01 00:07:23,8.117557,139.068239,NaN,78.050,5.0,8.0,NaN,NaN
4,Outdoor Running,2026-01-26 19:15,2026-01-26 19:48,1900-01-01 00:33:16,4.05637,148.117647,164,1900-01-01 00:08:12,7.315523,129.247187,NaN,66.872,61.0,80.0,NaN,NaN

In [27]:
data.dtypes

Type                              str
Start                             str
End                               str
Duration               datetime64[us]
Distance                      float64
Average Heart Rate            float64
Max Heart Rate                  int64
Average Pace           datetime64[us]
Average Speed                 float64
Average Cadence               float64
Active Energy                 float64
Total Energy                  float64
Elevation Ascended            float64
Elevation Descended           float64
Weather Temperature           float64
Weather Humidity              float64
dtype: object

- temperatur
-